{% set name = "tiatoolbox" %}
{% set version = "1.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 55b71b9423c57c8b533222552e11fe9addf04290763d1a6b241e55b17923c773

build:
  number: 0
  noarch: python
  entry_points:
    - tiatoolbox=tiatoolbox.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.8, <=3.11
  run:
    - albumentations >=1.3.0, <=1.3.1
    - bokeh >=3.1.1, <=3.3.2
    - click >=8.1.3, <=8.1.7
    - cudatoolkit >=11.8, <=12.1
    - defusedxml >=0.7.1, <=0.7.1
    - filelock >=3.9.0, <=3.13.1
    - flask >=2.2.2, <=2.3.2
    - flask-cors >=4.0.0, <=4.0.0
    - glymur >=0.12.7, <=0.12.9
    - imagecodecs >=2022.9.26, <=2023.9.18
    - joblib >=1.1.1, <=1.3.2
    - jupyterlab >=3.5.2, <=4.0.9
    - matplotlib-base >=3.6.2, <=3.8.2
    - numba >=0.57.0, <=0.58.1
    - numpy >=1.23.5, <=1.26.2
    - opencv >=4.6.0, <=4.8.1
    - openjpeg >=2.4.0, <=2.5.0
    - openslide-python >=1.2.0, <=1.3.1
    - pandas >=2.0.0, <=2.1.4
    - pillow >=9.3.0, <=10.1.0
    - pixman >=0.39.0, <=0.42.2
    - pydicom >=2.3.1, <=2.4.4
    - python >=3.8, <=3.11
    - pytorch >=2.1.0, <=2.1.2
    - pyyaml >=6.0, <=6.0.1
    - requests >=2.28.1, <=2.31.0
    - scikit-image >=0.20, <=1.11.4
    - scikit-learn >=1.2.0, <=1.3.2
    - scipy >=1.8.0, <=1.11.4
    - shapely >=2.0.0, <=2.0.2
    - SimpleITK >=2.3.0, <=2.3.1
    - sphinx >=5.3.0, <=7.2.6
    - tifffile >=2022.10.10, <=2023.12.9
    - torchvision >=0.15.0, <=0.16.2
    - tqdm >=4.64.1, <=4.66.1
    - umap-learn >=0.5.3, <=0.5.5
    - wsidicom >=0.7.0, <=0.17.0
    - zarr >=2.13.3, <=2.16.1

test:
  imports:
    - tiatoolbox
    - tiatoolbox.annotation
  commands:
    - tiatoolbox --help
  requires:
    - pip

about:
  home: https://github.com/TissueImageAnalytics/tiatoolbox
  summary: Computational pathology toolbox developed by TIA Lab.
  license: BSD-3-Clause
  license_file: {{ RECIPE_DIR if RECIPE_DIR is defined else '' }}/LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
    - shaneahmed
    - John-P
