{% set name = "tiatoolbox" %}
{% set version = "1.6.0" %}
{% set python_min = "3.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a775e8a0fd7e1a7cc39774314fd15c5531339c90fb0054d70d118ecd90872935

build:
  number: 0
  noarch: python
  entry_points:
    - tiatoolbox=tiatoolbox.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
  run:
    - albumentations >=1.3.0, <=1.4.21
    - bokeh >=3.1.1, <3.6.0
    - click >=8.1.3, <=8.1.7
    - defusedxml >=0.7.1, <=0.7.1
    - filelock >=3.9.0, <=3.16.1
    - flask >=2.2.2, <=3.1.0
    - flask-cors >=4.0.0, <=5.0.0
    - glymur >=0.12.7, <=0.13.6
    - imagecodecs >=2022.9.26, <=2024.9.22
    - joblib >=1.1.1, <=1.4.2
    - jupyterlab >=3.5.2, <=4.3.2
    - matplotlib-base >=3.6.2, <=3.9.3
    - numba >=0.57.0, <=0.60.0
    - numpy >=1.23.5, <2.0.0
    - opencv >=4.6.0, <=4.10.0
    - openjpeg >=2.4.0, <=2.5.3
    - openslide-python >=1.2.0, <=1.4.1
    - pandas >=2.0.0, <=2.2.3
    - pillow >=9.3.0, <=11.0.0
    - pixman >=0.39.0, <=0.44.2
    - pydicom >=2.3.1, <=3.0.1
    - python >={{ python_min }}
    - pytorch >=2.0.0, <=2.5.1
    - pyyaml >=6.0, <=6.0.2
    - requests >=2.28.1, <=2.32.3
    - scikit-image >=0.20, <=0.24.0
    - scikit-learn >=1.2.0, <=1.5.2
    - scipy >=1.8, <=1.14.1
    - shapely >=2.0.0, <=2.0.6
    - SimpleITK >=2.2.1, <=2.4.0
    - sphinx >=5.3.0, <=8.1.3
    - tifffile >=2022.10.10, <=2024.9.20
    - timm >=1.0.3, <=1.0.12
    - torchvision >=0.15.0, <=0.20.1
    - tqdm >=4.64.1, <=4.67.1
    - umap-learn >=0.5.3, <=0.5.7
    - wsidicom >=0.18.0, <=0.22.0
    - zarr >=2.13.3, <=2.18.3

test:
  imports:
    - tiatoolbox
    - tiatoolbox.annotation
  commands:
    - tiatoolbox --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/TissueImageAnalytics/tiatoolbox
  summary: Computational pathology toolbox developed by TIA Lab.
  license: BSD-3-Clause
  license_file: {{ RECIPE_DIR if RECIPE_DIR is defined else '' }}/LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
    - shaneahmed
    - John-P
