{% set name = "tiatoolbox" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e18f00ae87feaaedf8483e27332500de0047d824736a6ef5999cb47040ce511a

build:
  number: 0
  noarch: python
  entry_points:
    - tiatoolbox=tiatoolbox.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.7
  run:
    - albumentations >=1.2.0, <=1.3.0
    - click >=8.1.0, <=8.1.3
    - cudatoolkit >=11.3, <=11.7
    - defusedxml >=0.6.0, <=0.7.1
    - flask >=2.2.2, <=2.2.3
    - glymur >=0.11.7, <=0.12.2
    - imagecodecs >=2021.11.20, <=2023.1.23
    - joblib >=1.1.0, <=1.2.0
    - jupyterlab >=3.4.8, <=3.6.1
    - matplotlib-base >=3.5.3, <=3.7.0
    - numpy >=1.21.6, <1.24
    - opencv >=4.6.0, <=4.7.0
    - openjpeg >=2.4.0, <=2.5.0
    - openslide-python >=1.1.2, <=1.2.0
    - pandas >=1.3.5, <=1.5.3
    - pillow >=9.2.0, <=9.4.0
    - pixman >=0.39.0, <=0.40.0
    - pydicom >=2.3.0, <=2.3.1
    - python >=3.7, <3.11
    - pytorch >=1.13.0, <=1.13.1
    - pyyaml >=5.4, <=6.0
    - requests >=2.28.1, <=2.28.2
    - scikit-image >=0.19.0, <=0.19.3
    - scikit-learn >=1.0.2, <=1.2.1
    - scipy >=1.7.3, <=1.10.1
    - shapely >=1.8.5, <2.0.0
    - SimpleITK >=2.1.1, <=2.2.1
    - sphinx >=4.3.2, <=6.1.3
    - tifffile >=2021.11.2, <=2023.2.28
    - torchvision >=0.13.0, <=0.14.1
    - tqdm >=4.63.0, <=4.64.1
    - umap-learn >=0.5.0, <0.5.3
    - wsidicom >=0.3.2, <0.7.0
    - zarr >=2.12.0, <=2.14.2

test:
  imports:
    - tiatoolbox
    - tiatoolbox.annotation
  commands:
    - tiatoolbox --help
  requires:
    - pip

about:
  home: https://github.com/TissueImageAnalytics/tiatoolbox
  summary: Computational pathology toolbox developed by TIA Lab.
  license: BSD-3-Clause
  license_file: {{ RECIPE_DIR if RECIPE_DIR is defined else '' }}/LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
    - shaneahmed
    - John-P
