{% set name = "tiatoolbox" %}
{% set version = "1.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 55b71b9423c57c8b533222552e11fe9addf04290763d1a6b241e55b17923c773

build:
  number: 0
  noarch: python
  entry_points:
    - tiatoolbox=tiatoolbox.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.8, <=3.11
  run:
    - albumentations
    - bokeh
    - click
    - cudatoolkit
    - defusedxml
    - filelock
    - flask
    - flask-cors
    - glymur
    - imagecodecs
    - joblib
    - jupyterlab
    - matplotlib-base
    - numba
    - numpy
    - opencv
    - openjpeg
    - openslide-python
    - pandas
    - pillow
    - pixman
    - pydicom
    - python >=3.8, <=3.11
    - pytorch
    - pyyaml
    - requests
    - scikit-image
    - scikit-learn
    - scipy
    - shapely
    - SimpleITK
    - sphinx
    - tifffile
    - torchvision
    - tqdm
    - umap-learn
    - wsidicom
    - zarr

test:
  imports:
    - tiatoolbox
    - tiatoolbox.annotation
  commands:
    - tiatoolbox --help
  requires:
    - pip

about:
  home: https://github.com/TissueImageAnalytics/tiatoolbox
  summary: Computational pathology toolbox developed by TIA Lab.
  license: BSD-3-Clause
  license_file: {{ RECIPE_DIR if RECIPE_DIR is defined else '' }}/LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
    - shaneahmed
    - John-P
