{% set name = "tiatoolbox" %}
{% set version = "1.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 55b71b9423c57c8b533222552e11fe9addf04290763d1a6b241e55b17923c773

build:
  number: 0
  noarch: python
  entry_points:
    - tiatoolbox=tiatoolbox.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.8, <=3.11
  run:
    - albumentations >=1.2.0, <=1.3.0
    - click >=8.1.0, <=8.1.3
    - cudatoolkit >=11.7, <=11.8
    - defusedxml >=0.6.0, <=0.7.1
    - flask >=2.2.2, <=2.3.2
    - glymur >=0.12.1, <=0.12.5
    - imagecodecs >=2022.9.26, <=2023.3.16
    - joblib >=1.1.1, <=1.2.0
    - jupyterlab >=3.5.2, <=3.6.3
    - matplotlib-base >=3.6.2, <=3.7.1
    - numpy >=1.23.5, <1.24.3
    - opencv >=4.6.0, <=4.7.0
    - openjpeg >=2.4.0, <=2.5.0
    - openslide-python >=1.2.0, <=1.2.0
    - pandas >=2.0.0, <=2.0.1
    - pillow >=9.2.0, <=9.5.0
    - pixman >=0.39.0, <=0.40.0
    - pydicom >=2.3.1, <=2.3.1
    - python >=3.8, <=3.11
    - pytorch >=1.13.0, <=2.0.0
    - pyyaml >=6.0, <=6.0
    - requests >=2.28.1, <=2.30.0
    - scikit-image >=0.20.0, <=0.20.0
    - scikit-learn >=1.2.0, <=1.2.2
    - scipy >=1.8.0, <=1.10.1
    - shapely >=2.0.0, <=2.0.1
    - SimpleITK >=2.2.1, <=2.2.1
    - sphinx >=5.3.0, <=7.0.0
    - tifffile >=2022.10.10, <=2023.4.12
    - torchvision >=0.13.0, <=0.15.1
    - tqdm >=4.64.1, <=4.65.0
    - umap-learn >=0.5.0, <=0.5.3
    - wsidicom >=0.7.0, <=0.9.0
    - zarr >=2.13.3, <=2.14.2

test:
  imports:
    - tiatoolbox
    - tiatoolbox.annotation
  commands:
    - tiatoolbox --help
  requires:
    - pip

about:
  home: https://github.com/TissueImageAnalytics/tiatoolbox
  summary: Computational pathology toolbox developed by TIA Lab.
  license: BSD-3-Clause
  license_file: {{ RECIPE_DIR if RECIPE_DIR is defined else '' }}/LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
    - shaneahmed
    - John-P
